### ISSUE TITLE
Add support for Top Bar, Sticky Functionality

### ISSUE THREAD

**Issue by antonyisoardi** [ractive-foundation/ractive-foundation#106]
http://foundation.zurb.com/docs/components/topbar.html

Sticky Top Bar
You may also wrap your top bar in div class="sticky" and put it anywhere within your markup. When the navigation hits the top of the browser, it will act like the fixed top bar and stick to the top as users continue to scroll.

**Comment by ScottMaclure** [comment]
Done - you can see it here:

http://ractive-foundation.github.io/ractive-foundation/data.html
