### ISSUE TITLE
Create ux-orbit component

### ISSUE THREAD

**Issue by ScottMaclure** [ractive-foundation/ractive-foundation#112]
http://foundation.zurb.com/docs/components/orbit.html

See `page_swipe_demo` branch to get started. Rename and update.

Must-have
- Use `ractive-touch` (with `Hammer`) for swipe events.
- Unlimited slides.
- Don't care about the content of the slides, that's up to the content creator.
- Prev/next buttons
- Page indicators

Nice-to-have
- Accessible
- Real-time dragging rather than "swipe" event
- Caption support

Don't-bother
- Timer etc (because F that)

**Comment by nathf** [comment]
Is `Hammer` the best option for touch? [iscrolljs](http://iscrolljs.com/) is a good touch library that would provide multiple item scrolling (as you would expect on a mobile device).

**Comment by nathf** [comment]
Closing as this exists
