### ISSUE TITLE
Evaluate/Use jspm.io for deps mgmt

### ISSUE THREAD

**Issue by ScottMaclure** [ractive-foundation/ractive-foundation#12]
Note: Also supports bundling

**Comment by ScottMaclure** [comment]
@pvshum @nathf check this out:

https://github.com/jspm/jspm-cli/wiki/Production-Workflows

**Comment by pvshum** [comment]
Have tested on my machine (Win 8.1, node-v0.10.28-x64)
Had issues running `jspm` command:

**Comment by pvshum** [comment]
Opinion: Park jspm for now and use something more stable.
https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage
