### ISSUE TITLE
ux-tabarea active fails when page loaded with #anchor

### ISSUE THREAD

**Issue by antonyisoardi** [ractive-foundation/ractive-foundation#129]
When a page is loaded with a URL containing a hash (#) anchor, ux-tablink and ux-tabpane 'active' state is ignored in page render.

**Comment by nathf** [comment]
Hmm.. seems to be a issue with the deeplinking (https://github.com/ractive-foundation/ractive-foundation/blob/master/src/components/ux-tablinks/ux-tablinks.js#L6). 

I'll fix this up in the morning, so that if the hash doesn't match a tab the defined state is respected.

**Comment by antonyisoardi** [comment]
Thanks, Nath.

Also, not sure if you need to but test with multiple tabarea instances on the same page if possible :)

**Comment by pvshum** [comment]
Yes this need to be fixed. Seeing direct impact on the pages with client
side routing #!/foo, #!/bar

**Comment by nathf** [comment]
This issue should be resolved. Please re-open if I'm wrong.
