### ISSUE TITLE
'class' attribute is inherited by ux-header from parent 

### ISSUE THREAD

**Issue by antonyisoardi** [ractive-foundation/ractive-foundation#130]
When applying a class to the parent of ux-header, that class is then applied to ux-header.

EG.

```
<ux-row>
    <ux-col class="large-8">
        <ux-header level="1">Heading</ux-header>
    </ux-col>
<ux-row>
```

==>

```
<div class="row">
    <div class="large-8 columns">
        <h1 class="large-8">Heading</h1>
    </div>
</div>
```

**Comment by nathf** [comment]
The same should apply for ID.

**Comment by nathf** [comment]
Can't seem to replicate this in an isolated test. I'm using this [fiddle](http://jsfiddle.net/q441af5o/).

Can you reproduce there so I can see the use case?

**Comment by nathf** [comment]
@antonyisoardi any update here?

**Comment by antonyisoardi** [comment]
Cannot replicate at this time. Close the issue. Will raise again if I spot it.

Thanks
