### ISSUE TITLE
README.md doesn't tell how to use ractive-foundation

### ISSUE THREAD

**Issue by ivanwills** [ractive-foundation/ractive-foundation#137]
The README.md file really needs to tell people now to use ractive-foundation not just how to add to it.

**Comment by ScottMaclure** [comment]
Sounds like a good opportunity to write one :)

On 7 June 2015 at 19:16, Ivan Wills notifications@github.com wrote:

> The README.md file really needs to tell people now to use
> ractive-foundation not just how to add to it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ractive-foundation/ractive-foundation/issues/137.

## 

Scott Maclure
Web Applications Developer, Usability Enthusiast
http://scott.maclure.com.au/
[M] +61(0)424 275 065

**Comment by ivanwills** [comment]
I will once I know how to do it (in a better fashion than I currently have).

**Comment by nathf** [comment]
@ivanwills Please check the latest release. Can close accordingly

**Comment by ScottMaclure** [comment]
Closing this - assumed complete
