### ISSUE TITLE
The published npm package requires you to build it.

### ISSUE THREAD

**Issue by ivanwills** [ractive-foundation/ractive-foundation#138]
It probably would be good if there published package had the build js and css files so you don't have to do an `npm install && grunt build` to be able to use it. (also would save a significant quantity of downloaded dependencies)

**Comment by ivanwills** [comment]
Correction not even sure how to generate the css.

**Comment by pvshum** [comment]
Agree. We have dist folder exactly for that. There's no CSS file there at
the moment as ractive-foundation is using Foundation v5 CSS.

**Comment by nathf** [comment]
Latest release generates all required files in dist.
