### ISSUE TITLE
Add gulp clean task

### ISSUE THREAD

**Issue by ScottMaclure** [ractive-foundation/ractive-foundation#14]

**Comment by ivanwills** [comment]
how would this be different to git clean? What would it clean?

**Comment by ScottMaclure** [comment]
The main idea was to scrub the public folder before each build, to deal
with orphan files etc automatically.

**Comment by ScottMaclure** [comment]
Except for index.html obviously. Git clean -df sounds good!

**Comment by ScottMaclure** [comment]
Except that it needs to be limited to /public

**Comment by ScottMaclure** [comment]
This is now in master.
