### ISSUE TITLE
Make Ractive Foundation a compatible Ractive plugin

### ISSUE THREAD

**Issue by nathf** [ractive-foundation/ractive-foundation#140]
This will essentially nullify most of the `standalone` work.

But we should be compatible with the library we are extending off (in the plugin sense).

http://docs.ractivejs.org/latest/ractive-defaults - will suffice, thus retiring `forge` at a very early age

**Comment by nathf** [comment]
As part of this task, we should be providing only one `ractivef.js` file, which has the capabilities of handling all types (global, AMD, CommonJS)

**Comment by ivanwills** [comment]
A better/simpler version check:

``` js
var compareVersions = function (installed, required) {
    installed = installed.split(/[.]/).map(function(val) {
        return val.length > 2 ? val : val.length > 1 ? '0' + val : '00' + val;
    }).join('.');
    required = required.split(/[.]/).map(function(val) {
        return val.length > 2 ? val : val.length > 1 ? '0' + val : '00' + val;
    }).join('.');
    return installed >= required;
}
```

This will compare dotted decimal version with individual numbers up to 999.

**Comment by nathf** [comment]
Feel free to commit that @ivanwills  :)
