### ISSUE TITLE
Can't set class to ux-tabarea and ux-tablinks

### ISSUE THREAD

**Issue by antonyisoardi** [ractive-foundation/ractive-foundation#150]
Need to be able to apply different CSS to ux-tabarea and ux-tablinks components

**Comment by nathf** [comment]
+1 for this.

There are a few other components that need this as well. Probably all of them that don't support it, to be honest.

**Comment by nathf** [comment]
See https://github.com/ractive-foundation/ractive-foundation/pull/154

**Comment by nathf** [comment]
@antonyisoardi This will be included in v0.0.31
