### ISSUE TITLE
gulp wing - use node-getopt-long

### ISSUE THREAD

**Issue by ScottMaclure** [ractive-foundation/ractive-foundation#22]

**Comment by pvshum** [comment]
Does it change anything in the usage api syntax ?

**Comment by ScottMaclure** [comment]
Nope, only the internals.

**Comment by ivanwills** [comment]
it does mean that you can type

```
$ gulp wing --help
```

And get somewhat helpful output.

**Comment by pvshum** [comment]
Thanks, updated README.md
https://github.com/themacclesoft/ractive-foundation/pull/29
