### ISSUE TITLE
Add jshint step to gulp (re)build process

### ISSUE THREAD

**Issue by ScottMaclure** [ractive-foundation/ractive-foundation#37]
Don't allow re-build if jshint fails. Use `.jshintrc` file.

Make use of `gutil.beep()`?

(https://github.com/gulpjs/gulp-util)

**Comment by nathf** [comment]
Not sure if its just my flavour of linux but `gutil.beep()` and `beepbeep` package do not work. They do on OS X though. I would suggest for consistencies sake we possibly shift from `beep` to a notifier?

https://www.npmjs.com/package/node-notifier

@pvshum @ScottMaclure thoughts?

**Comment by ScottMaclure** [comment]
Sounds good to me.

**Comment by pvshum** [comment]
Agreed

**Comment by ScottMaclure** [comment]
Merged.
