### ISSUE TITLE
Add pre exec task to default task.

### ISSUE THREAD

**Issue by nathf** [ractive-foundation/ractive-foundation#44]
Automatically install npm / bower on default task.

https://www.npmjs.com/package/gulp-install

**Comment by pvshum** [comment]
Agreed! We need a **gulp** task to install **npm** so we can install **gulp**. Oh wait...

**Comment by nathf** [comment]
@pvshum It's for convenience, when a new feature (dependency) is added to the codebase and I don't (and shouldn't) have to think do I need to run `npm install` or `bower install` ? :smile:

**Comment by pvshum** [comment]
@nathf Agree, any automation is good.

**Comment by ScottMaclure** [comment]
No plan for bower at this time, yes? Just checking

**Comment by ScottMaclure** [comment]
Q) Shall we consider npm shrinkwrap soon?

**Comment by nathf** [comment]
I was just generalising with bower :smile:.

When the gulp file is complete (for now) we could look at shrinkwrap.

**Comment by pvshum** [comment]
@nathf @ScottMaclure shrinkwrap would be good.
Q) Does it mean we park #12 for now?

**Comment by ScottMaclure** [comment]
#12 still relevant, at least to evaluate, in particular the bundling features.

**Comment by ScottMaclure** [comment]
@nathf what do you think of PR #47 ?

**Comment by nathf** [comment]
Closed with merge of #47
