### ISSUE TITLE
Components: ux-accordion: Click on content causes accordion item to collapse.

### ISSUE THREAD

**Issue by pvshum** [ractive-foundation/ractive-foundation#53]
**How to reproduce:**
Open page with **ux-accordion** rendered
Click on accordion item content (ux-content)
**Expected behaviour:** no changes.
**Actual behaviour:** Accordion item content (ux-content) got collapsed

**Comment by ScottMaclure** [comment]
This one is tricky. Something we've discussed already - dynamic proxy event names.

Consider this markup:

```
<ux-accordionitem active="true">
    <ux-anchor>Testing an anchor1</ux-anchor>
    <ux-content>Here is the active content for 1</ux-content>
</ux-accordionitem>
```

`ux-anchor` is where the click event needs to be declared, not `ux-accordionitem` (where it currently is).

Options:
- `ux-accordionitem` should listen for the click event from `ux-anchor`, then fire the `changeAccordion` proxy event, and allow ux-accordion's current code to work as expected.
- Define a way for a component to pass a proxy name down to a generic sub-component. (NO we should just catch on the bubble and wrap in semantic event for parent components)
- Define a new component, `ux-accordionitem-title` (or similar), which is basically a clone of `ux-anchor` but with `on-click="changeAccordion"` added. (NO for this situation)
- Update all markup to explicitly name the proxy event name (NO)

**Comment by steven-bruce-au** [comment]
Think ive already done it, not pushed yet

**Comment by ScottMaclure** [comment]
@pvshum @nathf @steven-bruce-au, here's the relevant code which translates a lower-level proxy event to custom event:

In `ux-accordionitem.js`:

```
anchor.on('anchorClicked', function (e) {
    this.fire('changeAccordion', this);
    return false;
}.bind(this));
```

This means that I didn't need to chain down through components at the accordion level.

Odd behaviour was caused through various uses of `>content` and `yield` in certain situations. I think we need to look at this more closely.
