### ISSUE TITLE
Add support for "datamodel" driven components.

### ISSUE THREAD

**Issue by ScottMaclure** [ractive-foundation/ractive-foundation#56]
Spoke with @pvshum and we chose "datamodel" as the "reserved" property to trigger this behaviour. I figure "data" is a little too generic (usage meters, anyone?).

I'm going to start with this JSON:

```
{
    "class": "label-right",
    "items": [
        { "href": "/", "src": "images/fi-home.svg", "label": "Home" },
        { "href": "/path/to/blah", "src": "images/fi-bookmark.svg", "label": "Bookmark" },
        { "src": "images/fi-info.svg", "label": "Info", "class": "disabled" },
        { "src": "images/fi-mail.svg", "label": "Mail" },
        { "src": "images/fi-like.svg", "label": "Like" }
    ]
}
```

I ran that through `_.escape(JSON.stringify(data));` to produce the below:

```
<ux-iconbar datamodel="{&quot;class&quot;:&quot;label-right&quot;,&quot;items&quot;:[{&quot;href&quot;:&quot;/&quot;,&quot;src&quot;:&quot;images/fi-home.svg&quot;,&quot;label&quot;:&quot;Home&quot;},{&quot;href&quot;:&quot;/path/to/blah&quot;,&quot;src&quot;:&quot;images/fi-bookmark.svg&quot;,&quot;label&quot;:&quot;Bookmark&quot;},{&quot;src&quot;:&quot;images/fi-info.svg&quot;,&quot;label&quot;:&quot;Info&quot;,&quot;class&quot;:&quot;disabled&quot;},{&quot;src&quot;:&quot;images/fi-mail.svg&quot;,&quot;label&quot;:&quot;Mail&quot;},{&quot;src&quot;:&quot;images/fi-like.svg&quot;,&quot;label&quot;:&quot;Like&quot;}]}"></ux-iconbar>
```

Note that auto-documentation support will come later.

**Comment by ScottMaclure** [comment]
This hbs file works as expected, note the use of dot-notation to restrict context (i.e. not use parents'):

```
<div class="icon-bar {{upNum}} {{class}}" role="navigation">
    {{#if isDataModel}}
        {{#items}}
            <ux-iconbaritem href="{{.href}}" src="{{.src}}" label="{{.label}}" class="{{.class}}"></ux-iconbaritem>
        {{/items}}
    {{else}}
        {{yield}}
    {{/if}}
</div>
```

This approach works, but data from parent bleeds down into child:

```
<div class="icon-bar {{upNum}} {{class}}" role="navigation">
    {{#if isDataModel}}
        {{#items}}
            <ux-iconbaritem datamodel="{{.}}"></ux-iconbaritem>
        {{/items}}
    {{else}}
        {{yield}}
    {{/if}}
</div>
```

Which results in css classes from iconbar being added to the child items.

@nathf @pvshum isolated time?

**Comment by steven-bruce-au** [comment]
I assume the "isolated" option doesn't help here

http://docs.ractivejs.org/latest/components

**Comment by nathf** [comment]
@ScottMaclure Is there a contextual difference between `{{.}}` and `{{this}}` inside the loop?

**Comment by ScottMaclure** [comment]
@nathf I assume they're the same. Should check.

I've pushed an update using `isolated: true` on `ux-iconbaritem`, and things are now working as intended, both for datamodel components (data.html) and static components (index.html).

**Comment by ScottMaclure** [comment]
Basic support has been added, so closing this issue.

Am currently adding datamodel support to `ux-accordion`. Dealing with an issue with `onchange` firing in a component before `oninit` has run.
