### ISSUE TITLE
autodocs improvements

### ISSUE THREAD

**Issue by ScottMaclure** [ractive-foundation/ractive-foundation#64]
Fix template layout to work nicely on mobile (we can re-do nav later)
gulp-wing needs to create all files needed for autodocs.
use-cases don't seem to be watched
Manifest: If no events, either say "no events" or don't render that section.

**Comment by pvshum** [comment]
See PR above.
It doesn't have code for **gulp-wing needs to create all files needed for autodocs.**
Taking it as a separate task at it will require more canges
