### ISSUE TITLE
gulp-wing needs to create all files needed for autodocs

### ISSUE THREAD

**Issue by pvshum** [ractive-foundation/ractive-foundation#66]
This includes JSON files in use-cases folder
README.md
and manifest.json

**Comment by pvshum** [comment]
Challenges to solve here:
- Change the way gulpWing renaming files. Some filenames need  to be preserved (manifest.json, use-cases/*.json)
- Teach gulpWing to support nested folders (use-cases)

**Comment by nathf** [comment]
@pvshum This should be complete now?

**Comment by nathf** [comment]
Closing. Re-open if doesn't meet the requirements
