### ISSUE TITLE
Test suite muddles up test execution for components

### ISSUE THREAD

**Issue by ScottMaclure** [ractive-foundation/ractive-foundation#93]
Run `npm test` and look at the output:

```
Feature: ux-off-canvas test suite

  Scenario: Loading ux-off-canvas                                            # src/components/ux-off-canvas/ux-off-canvas.feature:3
    Then the element "button" should have the "role" of "button"             # src/components/ux-button/ux-button.feature:7
```

Solution is to separately execute test suites for each component.

**Comment by nathf** [comment]
This issue should be resolved. There was a function that was calling callback twice (one without awaiting the assertion).

**Comment by nathf** [comment]
Closing this as it should be resolved. Re-open if its persisting for you.
